// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Item in *Blitz Tournament Result → results*
 */
export interface BlitzTournamentResultDocumentDataResultsItem {
  /**
   * Name field in *Blitz Tournament Result → results*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blitz_tournament_result.results[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Score field in *Blitz Tournament Result → results*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blitz_tournament_result.results[].score
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  score: prismic.KeyTextField
}

/**
 * Content for Blitz Tournament Result documents
 */
interface BlitzTournamentResultDocumentData {
  /**
   * tournament date field in *Blitz Tournament Result*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blitz_tournament_result.tournament_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  tournament_date: prismic.DateField

  /**
   * results field in *Blitz Tournament Result*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blitz_tournament_result.results[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  results: prismic.GroupField<
    Simplify<BlitzTournamentResultDocumentDataResultsItem>
  >
}

/**
 * Blitz Tournament Result document from Prismic
 *
 * - **API ID**: `blitz_tournament_result`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlitzTournamentResultDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlitzTournamentResultDocumentData>,
    'blitz_tournament_result',
    Lang
  >

/**
 * Item in *Blog Post → tags*
 */
export interface BlogPostDocumentDataTagsItem {
  /**
   * tag field in *Blog Post → tags*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: general
   * - **API ID Path**: blog_post.tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tag: prismic.SelectField<
    | 'general'
    | 'glossary'
    | 'opening'
    | 'middlegame'
    | 'endgame'
    | 'match-report',
    'filled'
  >
}

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * tags field in *Blog Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tags: prismic.GroupField<Simplify<BlogPostDocumentDataTagsItem>>

  /**
   * Author field in *Blog Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author: prismic.TitleField

  /**
   * Blog Content field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.blog_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blog_content: prismic.RichTextField

  /**
   * PGN field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.pgn
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pgn: prismic.KeyTextField
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    'blog_post',
    Lang
  >

/**
 * Item in *Calendar → Events*
 */
export interface CalendarDocumentDataEventsItem {
  /**
   * Title field in *Calendar → Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.events[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * date field in *Calendar → Events*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.events[].date
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date: prismic.TimestampField

  /**
   * Description field in *Calendar → Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.events[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Content for Calendar documents
 */
interface CalendarDocumentData {
  /**
   * Events field in *Calendar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.events[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  events: prismic.GroupField<Simplify<CalendarDocumentDataEventsItem>>
}

/**
 * Calendar document from Prismic
 *
 * - **API ID**: `calendar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalendarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CalendarDocumentData>,
    'calendar',
    Lang
  >

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * date field in *Event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: event.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date: prismic.TimestampField

  /**
   * description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * public field in *Event*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event.public
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  public: prismic.BooleanField
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<EventDocumentData>, 'event', Lang>

/**
 * Item in *Gallery → Images*
 */
export interface GalleryDocumentDataImagesItem {
  /**
   * Image field in *Gallery → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Image Date field in *Gallery → Images*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.images[].image_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  image_date: prismic.DateField
}

/**
 * Content for Gallery documents
 */
interface GalleryDocumentData {
  /**
   * Images field in *Gallery*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<GalleryDocumentDataImagesItem>>
}

/**
 * Gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalleryDocumentData>,
    'gallery',
    Lang
  >

interface HomePageSectionsDocumentData {}

/**
 * Home Page Sections document from Prismic
 *
 * - **API ID**: `home_page_sections`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageSectionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageSectionsDocumentData>,
    'home_page_sections',
    Lang
  >

/**
 * Item in *Resource → videos*
 */
export interface ResourceDocumentDataVideosItem {
  /**
   * embed field in *Resource → videos*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.videos[].embed
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  embed: prismic.EmbedField
}

/**
 * Item in *Resource → pgns*
 */
export interface ResourceDocumentDataPgnsItem {
  /**
   * PGN File Name field in *Resource → pgns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.pgns[].pgn_file_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pgn_file_name: prismic.KeyTextField
}

/**
 * Content for Resource documents
 */
interface ResourceDocumentData {
  /**
   * title field in *Resource*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * type field in *Resource*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<'Video' | 'PGN' | 'Article'>

  /**
   * videos field in *Resource*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.videos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  videos: prismic.GroupField<Simplify<ResourceDocumentDataVideosItem>>

  /**
   * description field in *Resource*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * pgns field in *Resource*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: resource.pgns[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  pgns: prismic.GroupField<Simplify<ResourceDocumentDataPgnsItem>>
}

/**
 * Resource document from Prismic
 *
 * - **API ID**: `resource`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResourceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResourceDocumentData>,
    'resource',
    Lang
  >

export type AllDocumentTypes =
  | BlitzTournamentResultDocument
  | BlogPostDocument
  | CalendarDocument
  | EventDocument
  | GalleryDocument
  | HomePageSectionsDocument
  | ResourceDocument

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      BlitzTournamentResultDocument,
      BlitzTournamentResultDocumentData,
      BlitzTournamentResultDocumentDataResultsItem,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataTagsItem,
      CalendarDocument,
      CalendarDocumentData,
      CalendarDocumentDataEventsItem,
      EventDocument,
      EventDocumentData,
      GalleryDocument,
      GalleryDocumentData,
      GalleryDocumentDataImagesItem,
      HomePageSectionsDocument,
      HomePageSectionsDocumentData,
      ResourceDocument,
      ResourceDocumentData,
      ResourceDocumentDataVideosItem,
      ResourceDocumentDataPgnsItem,
      AllDocumentTypes,
    }
  }
}
